authorName: default
experimentName: test_nni
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
trainingServicePlatform: local
# 搜索空间文件
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
# 运行的命令，以及 Trial 代码的路径
trial:
  command: python main_nni.py
  codeDir: .
  gpuNum: 2